HOMEDIR = pwd;
% savepath([HOMEDIR, 'pathdef.m']);
% clear HOMEDIR;
addpath( HOMEDIR );
addpath([HOMEDIR, '/ADF']);
addpath([HOMEDIR, '/MBis']);
addpath([HOMEDIR, '/EIT']);
addpath([HOMEDIR, '/EIT/EIT_package_imlkh']);
addpath([HOMEDIR, '/EIT/Mesh2d_v24']);
addpath([HOMEDIR, '/Filt']);
addpath([HOMEDIR, '/ICA']);
addpath([HOMEDIR, '/Image']);
addpath([HOMEDIR, '/Cole']);
addpath([HOMEDIR, '/SCG']);
addpath([HOMEDIR, '/physionet']);
addpath([HOMEDIR, '/BA']);
addpath([HOMEDIR, '/Import']);
clear HOMEDIR;
% savepath( HOMEDIR );
% savepath([HOMEDIR, '/ADF']);
% savepath([HOMEDIR, '/MBis']);
% savepath([HOMEDIR, '/EIT']);
% savepath([HOMEDIR, '/EIT/EIT_package_imlkh']);
% savepath([HOMEDIR, '/EIT/Mesh2d_v24']);
% savepath([HOMEDIR, '/Filt']);
% savepath([HOMEDIR, '/ICA']);
% savepath([HOMEDIR, '/Image']);
% savepath([HOMEDIR, '/Cole']);
% savepath([HOMEDIR, '/SCG']);
% savepath([HOMEDIR, '/physionet']);